namespace SpriteKind {
    export const Proyectilenemigo = SpriteKind.create()
    export const EnemyTear = SpriteKind.create()
    export const Tear = SpriteKind.create()
    export const PowerUp = SpriteKind.create()
    export const Segidor = SpriteKind.create()
    export const Cofre = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (player2, enemy) {
    enemy.destroy()
    info.changeLifeBy(1)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Isac,
    [img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2d2ffff2dddddddd2ffff2d2ff...
        ...ff2df11fffddddddddf11fffd2ff...
        ...ff2df11fffddddddddf11fff22ff...
        ...ff22ffffffddffffddffffff22ff...
        ....ff2ffffffdffffffdffffff2ff....
        ....ff22ffff2df1111fd2ffff22ff....
        .....ff2999dddffffffddd9992ff.....
        .....ff2999dddddddddddd9992ff.....
        ......ff899dddddddddddd998ff......
        .......ff89dddddddddddd98ff.......
        ........fff82dddddddd28fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddddddfd2ff........
        .........ffffdd2ff2ddffff.........
        ..........fffdddff2ddfff..........
        ...........fffddff2dfff...........
        ............ffffffffff............
        .............fff..fff.............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2d2ffff2dddddddd2ffff2d2ff...
        ...ff2df11fffddddddddf11fffd2ff...
        ...ff2df11fffddddddddf11fff22ff...
        ...ff22ffffffddffffddffffff22ff...
        ....ff2ffffffdffffffdffffff2ff....
        ....ff22ffff2df1111fd2ffff22ff....
        .....ff2999dddffffffddd9992ff.....
        .....ff2999dddddddddddd9992ff.....
        ......ff899dddddddddddd998ff......
        .......ff89dddddddddddd98ff.......
        ........fff82dddddddd28fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2df222dddddfd2ff........
        .........ffff2d2ff2ddffff.........
        ..........fffdddff2ddfff..........
        ...........fffffff2dfff...........
        .............fffffffff............
        ..................fff.............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2d2ffff2dddddddd2ffff2d2ff...
        ...ff2df11fffddddddddf11fffd2ff...
        ...ff2df11fffddddddddf11fff22ff...
        ...ff22ffffffddffffddffffff22ff...
        ....ff2ffffffdffffffdffffff2ff....
        ....ff22ffff2df1111fd2ffff22ff....
        .....ff2999dddffffffddd9992ff.....
        .....ff2999dddddddddddd9992ff.....
        ......ff899dddddddddddd998ff......
        .......ff89dddddddddddd98ff.......
        ........fff82dddddddd28fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddddddfd2ff........
        .........ffffdd2ff2ddffff.........
        ..........fffdddff2ddfff..........
        ...........fffddff2dfff...........
        ............ffffffffff............
        .............fff..fff.............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2d2ffff2dddddddd2ffff2d2ff...
        ...ff2df11fffddddddddf11fffd2ff...
        ...ff22f11fffddddddddf11fffd2ff...
        ...ff22ffffffddffffddffffff22ff...
        ....ff2ffffffdffffffdffffff2ff....
        ....ff22ffff2df1111fd2ffff22ff....
        .....ff2999dddffffffddd9992ff.....
        .....ff2999dddddddddddd9992ff.....
        ......ff899dddddddddddd998ff......
        .......ff89dddddddddddd98ff.......
        ........fff82dddddddd28fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddd222fd2ff........
        .........ffffdd2ff2d2ffff.........
        ..........fffdd2ffdddfff..........
        ...........fffd2fffffff...........
        ............fffffffff.............
        .............fff..................
        `],
    200,
    true
    )
})
function Spawnenemies2 (Amaunt: number) {
    for (let index = 0; index < Amaunt; index++) {
        Mdmd = sprites.create(img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ......444444a.......
            .....4441444aa......
            .....4144444aa......
            .....1144444aa......
            .....1444444aa......
            .....444444aaa......
            .....44444aaaa......
            .....4444aaaaa......
            ......aaaaaaa.......
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            `, SpriteKind.Segidor)
        animation.runImageAnimation(
        Mdmd,
        [img`
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ....ffff...............ffff...
            ...f...ff.............ff...f..
            ...f.....f...........f.....f..
            ..f.......f.........f.......f.
            ..f.......f.........f.......f.
            ...f.......f.......f.......f..
            ...f.......f.......f.......f..
            ...f........f.....f........f..
            ...ff.......f.....f.......ff..
            ....f.......4444444.......f...
            .....ff....44144444a....ff....
            ......fff.444444444aa.fff.....
            ........f4114444444aaaf.......
            .........4144444444aaa........
            .........414444444aaaa........
            .........444444444aaaa........
            .........44444444aaaaa........
            .........44444444aaaaa........
            .........444444aaaaaaa........
            ..........aaaaaaaaaaa.........
            ...........aaaaaaaaa..........
            ............aaaaaaa...........
            ..............................
            ..............................
            ..............................
            `,img`
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ..............................
            ............4444444...........
            ...........44144444a..........
            ..ffffff..444444444aa..fffff..
            .ff....ff4114444444aaaff...ff.
            ff.......4144444444aaa......ff
            f........414444444aaaa.......f
            f......ff444444444aaaaf......f
            fff...ff.44444444aaaaa.f...fff
            ...fff...44444444aaaaa..fff...
            .........444444aaaaaaa........
            ..........aaaaaaaaaaa.........
            ...........aaaaaaaaa..........
            ............aaaaaaa...........
            ..............................
            ..............................
            ..............................
            `],
        100,
        true
        )
        tiles.placeOnRandomTile(Mdmd, assets.tile`myTile`)
        Mdmd.follow(Isac, 50)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Segidor, function (player2, enemy) {
    enemy.destroy()
    info.changeLifeBy(-1)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    shoot(TEAR_SPEED, 0)
    animation.runImageAnimation(
    Isac,
    [img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddffffddddff....
        ...ff2dddddddddddddf11fffddddff...
        ...ff2dddddddddddddf11fffddddff...
        ...ff2dddddddddddddffffffddddff...
        ...ff2dddddddddddddffffffddddff...
        ...ff22dddddddddddddffffddfffff...
        ....ff2ddddddddddddd999ddfffff....
        ....ff22dddddddddddd999ddf11ff....
        .....ff2dddddddddddd999ddffff.....
        .....ff2dddddddddddd999ddddff.....
        ......ff2ddddddddddd999dd2ff......
        .......ff2dddddddddd999d2ff.......
        ........fff22ddddddd998fff........
        .........ffff22222228ffff.........
        .......fffffffffffffffff..........
        ......fddddddffffffff.............
        ......f2222222ddd2dddff...........
        .......ffffff2ddd2dddff...........
        ...........ff2ddd2dddff...........
        ...........ff2ddd22ddff...........
        ...........ff2dddd222ff...........
        ............ff2dddffff............
        .............ff2ddfff.............
        ...............ffff...............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddffffddddff....
        ...ff2dddddddddddddf11fffddddff...
        ...ff2dddddddddddddf11fffddddff...
        ...ff2dddddddddddddffffffddddff...
        ...ff2dddddddddddddffffffddddff...
        ...ff22dddddddddddddffffddfffff...
        ....ff2ddddddddddddd999ddfffff....
        ....ff22dddddddddddd999ddf11ff....
        .....ff2dddddddddddd999ddffff.....
        .....ff2dddddddddddd999ddddff.....
        ......ff2ddddddddddd999dd2ff......
        .......ff2dddddddddd999d2ff.......
        ........fff22ddddddd998fff........
        .........ffff22222228ffff.........
        .......fffffffffffffffff..........
        ......fddddddffffffff.............
        ......f2222222dddddff.............
        .......ffffff2ddddddff............
        ...........ff2ddddddff............
        ...........ff2dddddddf............
        ...........ff2ddfddddff...........
        ............ff2ddffdddf...........
        .............ff2ff.fddff..........
        ..............ffff..ffff..........
        `],
    400,
    true
    )
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    shoot(0 - TEAR_SPEED, 0)
    animation.runImageAnimation(
    Isac,
    [img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddffffddddddddddddddff....
        ...ffddddfff11fddddddddddddd2ff...
        ...ffddddfff11fddddddddddddd2ff...
        ...ffddddffffffddddddddddddd2ff...
        ...ffddddffffffddddddddddddd2ff...
        ...fffffddffffddddddddddddd22ff...
        ....fffffdd999ddddddddddddd2ff....
        ....ff11fdd999dddddddddddd22ff....
        .....ffffdd999dddddddddddd2ff.....
        .....ffdddd999dddddddddddd2ff.....
        ......ff2dd999ddddddddddd2ff......
        .......ff2d999dddddddddd2ff.......
        ........fff899ddddddd22fff........
        .........ffff82222222ffff.........
        ..........fffffffffffffffff.......
        .............ffffffffddddddf......
        ...........ffddd2ddd2222222f......
        ...........ffddd2ddd2ffffff.......
        ...........ffddd2ddd2ff...........
        ...........ffdd22ddd2ff...........
        ...........ff222dddd2ff...........
        ............ffffddd2ff............
        .............fffdd2ff.............
        ...............ffff...............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddffffddddddddddddddff....
        ...ffddddfff11fddddddddddddd2ff...
        ...ffddddfff11fddddddddddddd2ff...
        ...ffddddffffffddddddddddddd2ff...
        ...ffddddffffffddddddddddddd2ff...
        ...fffffddffffddddddddddddd22ff...
        ....fffffdd999ddddddddddddd2ff....
        ....ff11fdd999dddddddddddd22ff....
        .....ffffdd999dddddddddddd2ff.....
        .....ffdddd999dddddddddddd2ff.....
        ......ff2dd999ddddddddddd2ff......
        .......ff2d999dddddddddd2ff.......
        ........fff899ddddddd22fff........
        .........ffff82222222ffff.........
        ..........fffffffffffffffff.......
        .............ffffffffddddddf......
        .............ffddddd2222222f......
        ............ffdddddd2ffffff.......
        ............ffdddddd2ff...........
        ............fddddddd2ff...........
        ...........ffddddfdd2ff...........
        ...........fdddffdd2ff............
        ..........ffddf.ff2ff.............
        ..........ffff..ffff..............
        `],
    400,
    true
    )
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    shoot(0, 0 - TEAR_SPEED)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    shoot(0, TEAR_SPEED)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (player2, enemy) {
    enemy.destroy()
    info.changeLifeBy(-1)
})
// ---------------- ENEMIGOS ----------------
function spawnEnemies (amount: number) {
    for (let index = 0; index < amount; index++) {
        enemy = sprites.create(img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ........fffffff.....
            .......ff1fff1ff....
            .......f111f111f....
            ...ffffff1fff1fffff.
            ..ff....ffffff....ff
            ..f.....f3333ff....f
            ...f...f333333ff..f.
            ....ffff3333333fff..
            .......f333333ff....
            .......f33333ff.....
            .......ff333ff......
            ........f33ff.......
            .........f3f........
            ..........f.........
            `, SpriteKind.Enemy)
        tiles.placeOnRandomTile(enemy, assets.tile`myTile`)
    }
    animation.runImageAnimation(
    enemy,
    [img`
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ............ffffffff..............
        ...........ff1ffff1ff.............
        ...........f111ff111f.............
        ..........fff1ffff1ffff...........
        ........ff...ffffff....ff.........
        ........f....f3333ff....f.........
        .........f..f333333ff..f..........
        ..........fff3333333fff...........
        ............f333333ff.............
        ............f33333ff..............
        ............ff333ff...............
        .............f33ff................
        ..............f3f.................
        ...............f..................
        `,img`
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        ..................................
        .......fff..ffffffff..fff.........
        .......f..fff1ffff1fff..f.........
        .......f..ff111ff111ff..f.........
        .......f....f1ffff1f...ff.........
        .......ff....ffffff...ff..........
        ........ff...f3333ff..f...........
        .........ffff333333ffff...........
        ............f3333333f.............
        ............f333333ff.............
        ............f33333ff..............
        ............ff333ff...............
        .............f33ff................
        ..............f3f.................
        ...............f..................
        `],
    100,
    true
    )
}
// ---------------- COLISIONES ----------------
sprites.onOverlap(SpriteKind.Tear, SpriteKind.Enemy, function (tear, enemy) {
    tear.destroy()
    enemy.destroy(effects.disintegrate, 100)
    info.changeScoreBy(1)
})
function shoot (vx: number, vy: number) {
    tear = sprites.create(img`
        . 9 1 9 9 9 9 8 . 
        9 1 9 9 9 9 9 8 8 
        9 1 9 9 9 9 9 8 8 
        9 1 9 9 9 9 9 8 8 
        9 9 9 9 9 9 9 8 8 
        9 9 9 9 9 9 9 8 8 
        9 9 9 9 9 9 8 8 8 
        8 8 8 8 8 8 8 8 8 
        . 8 8 8 8 8 8 8 . 
        `, SpriteKind.Tear)
    tear.setPosition(Isac.x, Isac.y)
    tear.setVelocity(vx, vy)
    tear.setFlag(SpriteFlag.AutoDestroy, true)
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Isac,
    [img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2dddddddddddddddddddddddff...
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2ddddddddddddddddddddd22ff...
        ...ff22dddddddddddddddddddd22ff...
        ....ff2dddddddddddddddddddd2ff....
        ....ff22dddddddddddddddddd22ff....
        .....ff2dddddddddddddddddd2ff.....
        .....ff2dddddddddddddddddd2ff.....
        ......ff2dddddddddddddddd2ff......
        .......ff2dddddddddddddd2ff.......
        ........fff22dddddddd22fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddddddfd2ff........
        .........ffffdd2ff2ddffff.........
        ..........fffdddff2ddfff..........
        ...........fffddff2dfff...........
        ............ffffffffff............
        .............fff..fff.............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2dddddddddddddddddddddddff...
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2ddddddddddddddddddddd22ff...
        ...ff22dddddddddddddddddddd22ff...
        ....ff2dddddddddddddddddddd2ff....
        ....ff22dddddddddddddddddd22ff....
        .....ff2dddddddddddddddddd2ff.....
        .....ff2dddddddddddddddddd2ff.....
        ......ff2dddddddddddddddd2ff......
        .......ff2dddddddddddddd2ff.......
        ........fff22dddddddd22fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddddddfd2ff........
        .........ffffdd2ff2ddffff.........
        ..........ffffddff2ddfff..........
        ...........fffffff2dfff...........
        .............fffffffff............
        ..................fff.............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2dddddddddddddddddddddddff...
        ...ff2dddddddddddddddddddddd2ff...
        ...ff2ddddddddddddddddddddd22ff...
        ...ff22dddddddddddddddddddd22ff...
        ....ff2dddddddddddddddddddd2ff....
        ....ff22dddddddddddddddddd22ff....
        .....ff2dddddddddddddddddd2ff.....
        .....ff2dddddddddddddddddd2ff.....
        ......ff2dddddddddddddddd2ff......
        .......ff2dddddddddddddd2ff.......
        ........fff22dddddddd22fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddddddfd2ff........
        .........ffffdd2ff2ddffff.........
        ..........fffdddff2ddfff..........
        ...........fffddff2dfff...........
        ............ffffffffff............
        .............fff..fff.............
        `,img`
        ..................................
        ..................................
        ...........ffffffffffff...........
        .........ffff22222222ffff.........
        ........fff2dddddddddd2fff........
        .......ff2dddddddddddddd2ff.......
        ......ff2dddddddddddddddd2ff......
        .....ff2dddddddddddddddddd2ff.....
        .....ffddddddddddddddddddddff.....
        ....ff2dddddddddddddddddddd2ff....
        ....ffddddddddddddddddddddddff....
        ...ff2dddddddddddddddddddddd2ff...
        ...ffddddddddddddddddddddddd2ff...
        ...ff2dddddddddddddddddddddd2ff...
        ...ff22ddddddddddddddddddddd2ff...
        ...ff22dddddddddddddddddddd22ff...
        ....ff2dddddddddddddddddddd2ff....
        ....ff22dddddddddddddddddd22ff....
        .....ff2dddddddddddddddddd2ff.....
        .....ff2dddddddddddddddddd2ff.....
        ......ff2dddddddddddddddd2ff......
        .......ff2dddddddddddddd2ff.......
        ........fff22dddddddd22fff........
        .........ffff22222222ffff.........
        ..........ffffffffffffff..........
        .........ff2dffffffffd2ff.........
        ........ff2dddddddddddd2ff........
        ........ff2dfddddddddfd2ff........
        ........ff2dfddddddddfd2ff........
        .........ffffdd2ff2ddffff.........
        ..........fffdd2ffddffff..........
        ...........fffd2fffffff...........
        ............fffffffff.............
        .............fff..................
        `],
    200,
    true
    )
})
function Powerup2 () {
    p = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . f f f f f . f f f f f . . 
        . . f f 4 4 4 f f f 4 4 4 f f . 
        . . f 4 4 4 4 4 f 4 4 4 4 4 f . 
        . . f 4 4 4 4 4 4 4 1 1 4 4 f . 
        . . f 4 4 4 4 4 4 4 1 1 4 4 f . 
        . . f 4 4 4 4 4 4 4 4 4 4 4 f . 
        . . f f 4 4 4 a a a 4 4 4 f f . 
        . . . f f 4 a a a a a 4 f f . . 
        . . . . f f a a a a a f f . . . 
        . . . . . f f a a a f f . . . . 
        . . . . . . f f a f f . . . . . 
        . . . . . . . f f f . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    tiles.placeOnRandomTile(p, assets.tile`myTile24`)
}
function spawnPowerUp () {
    p = sprites.create(img`
        . . . . . . f f f f . . . . . . 
        . . . . f f 4 4 4 4 f f . . . . 
        . . . f f 4 4 4 4 1 1 f f . . . 
        . . f f 4 4 4 4 4 1 1 1 f f . . 
        . f f 1 1 1 4 4 4 4 1 1 4 f f . 
        f f d 1 1 1 4 4 4 4 4 4 4 f f f 
        f a d d 1 4 4 4 4 4 1 1 1 a a f 
        f a a a 4 4 1 1 4 4 1 1 d d a f 
        f a a a a d d 1 1 4 a d d d a f 
        . f a a a a d d a a a a a a f . 
        . . f f a a a a a a a a f f . . 
        . . . . f f f f f f f f . . . . 
        . . . . . . f 1 1 f . . . . . . 
        . . . . . . f 1 1 f f . . . . . 
        . . . . . f f d 1 1 f . . . . . 
        . . . . . f d d 1 1 f . . . . . 
        `, SpriteKind.PowerUp)
    tiles.placeOnRandomTile(p, assets.tile`myTile24`)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.PowerUp, function (player2, p) {
    p.destroy()
    PLAYER_SPEED += 50
    controller.moveSprite(Isac, PLAYER_SPEED, PLAYER_SPEED)
    Isac.changeScale(-0.1, ScaleAnchor.Top)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Cofre, function (sprite, otherSprite) {
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.EnemyTear, function (player2, tear) {
    tear.destroy()
    info.changeLifeBy(-1)
})
// ---------------- COLISIONES ----------------
sprites.onOverlap(SpriteKind.Tear, SpriteKind.Segidor, function (tear, enemy) {
    tear.destroy()
    enemy.destroy(effects.disintegrate, 100)
    info.changeScoreBy(1)
})
let mySprite: Sprite = null
let tear2: Sprite = null
let p: Sprite = null
let tear: Sprite = null
let enemy: Sprite = null
let Mdmd: Sprite = null
let Isac: Sprite = null
let TEAR_SPEED = 0
let PLAYER_SPEED = 0
tiles.setCurrentTilemap(tilemap`level1`)
// ---------------- CONSTANTES ----------------
PLAYER_SPEED = 90
TEAR_SPEED = 150
let ENEMY_SPEED = 25
Isac = sprites.create(img`
    ..................................
    .............fffffffff............
    ...........ffffffffffff...........
    .........ffff22222222ffff.........
    ........fff2dddddddddd2fff........
    .......ff2dddddddddddddd2ff.......
    ......ff2dddddddddddddddd2ff......
    .....ff2dddddddddddddddddd2ff.....
    .....ffddddddddddddddddddddff.....
    ....ff2dddddddddddddddddddd2ff....
    ....ffddddddddddddddddddddddff....
    ...ff2dddddddddddddddddddddd2ff...
    ...ff2ddffffddddddddddffffdd2ff...
    ...ff2df11fffddddddddf11fffd2ff...
    ...ff22f11fffddddddddf11fff22ff...
    ...ff22ffffffddffffddffffff22ff...
    ....ff2ffffffdffffffdffffff2ff....
    ....ff22ffffddf1111fddffff22ff....
    .....ff2999dddffffffddd9992ff.....
    .....ff2999dddddddddddd9992ff.....
    ......ff899dddddddddddd998ff......
    .......ff98dddddddddddd98ff.......
    ........fff82dddddddd28fff........
    .........ffff22222222ffff.........
    ..........ffffffffffffff..........
    .........ff2dffffffffd2ff.........
    ........ff2dd22222222dd2ff........
    ........ff2df2dddddd2fd2ff........
    ........ff2dfddddddddfd2ff........
    .........ffffdd2ff2ddffff.........
    ..........fffdddff2ddfff..........
    ...........fffddff2dfff...........
    ............ffffffffff............
    .............fff..fff.............
    `, SpriteKind.Player)
controller.moveSprite(Isac, PLAYER_SPEED, PLAYER_SPEED)
tiles.placeOnRandomTile(Isac, assets.tile`myTile24`)
Isac.setStayInScreen(true)
info.setLife(5)
info.setScore(0)
scene.cameraFollowSprite(Isac)
pause(1000)
spawnEnemies(2)
// ---------------- IA ENEMIGOS (GLOBAL) ----------------
game.onUpdate(function () {
    for (let enemy2 of sprites.allOfKind(SpriteKind.Enemy)) {
        if (Isac.x > enemy2.x) {
            enemy2.x += ENEMY_SPEED / 50
        }
        if (Isac.x < enemy2.x) {
            enemy2.x -= ENEMY_SPEED / 50
        }
        if (Isac.y > enemy2.y) {
            enemy2.x += ENEMY_SPEED / 50
        }
        if (Isac.y < enemy2.y) {
            enemy2.y -= ENEMY_SPEED / 50
        }
        if (Math.percentChance(3)) {
            tear2 = sprites.create(img`
                . 4 1 4 4 4 4 a . 
                4 1 4 4 4 4 4 a a 
                4 1 4 4 4 4 4 a a 
                4 1 4 4 4 4 4 a a 
                4 4 4 4 4 4 4 a a 
                4 4 4 4 4 4 4 a a 
                4 4 4 4 4 4 a a a 
                a a a a a a a a a 
                . a a a a a a a . 
                `, SpriteKind.EnemyTear)
            tear2.setPosition(enemy2.x, enemy2.y)
            tear2.follow(Isac, 60)
            tear2.setFlag(SpriteFlag.AutoDestroy, true)
        }
    }
})
game.onUpdate(function () {
    if (sprites.allOfKind(SpriteKind.Segidor).length == 0) {
        Powerup2()
        Spawnenemies2(randint(3, 5))
    }
})
game.onUpdate(function () {
    if (sprites.allOfKind(SpriteKind.Enemy).length == 0) {
        spawnPowerUp()
        spawnEnemies(randint(0, 3))
    }
})
forever(function () {
    if (info.score() == 90) {
        mySprite = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . c b . . c b . . c b . . c b . 
            . c b e 5 c b e 5 c b e 5 c b . 
            . c b e 5 c b e 5 c b e 5 c b . 
            . c b e 5 c b e 5 c b e 5 c b . 
            . c b e 5 c b e 5 c b e 5 c b . 
            . c b e 5 c b b b b b e 5 c b . 
            . c b c c c c c c c b c c c b . 
            . c e 5 5 5 c f f c e 5 5 5 b . 
            . c e 5 5 5 c c c c e 5 5 5 b . 
            . c e 5 5 5 5 5 5 5 5 5 5 5 b . 
            . c e 5 5 5 5 5 5 5 5 5 5 5 b . 
            . c e 5 5 5 5 5 5 5 5 5 5 5 b . 
            . c e 5 5 5 5 5 5 5 5 5 5 5 b . 
            . c c c c c c c c c c c c c b . 
            `, SpriteKind.Cofre)
        tiles.placeOnRandomTile(mySprite, assets.tile`myTile24`)
    }
})
